FROM python:3.13

RUN pip install --upgrade pip
# Create a directory where the code is to be hosted
RUN mkdir /app
# Define the working directory in the container
WORKDIR /app
# Copy and install the requirements.
COPY requirements.txt /app/requirements.txt
RUN pip install -r requirements.txt
# Copy application code to the image
COPY . /app/

# Define environment variables
ENV host=0.0.0.0
ENV port=80
ENV dash_debug=False

CMD ["gunicorn", "-b", "0.0.0.0:80", "--workers", "4", "main:server"]
